server.port=8080

spring.application.name=ms-conta

# DataSource do lado command
app.datasource.command.jdbc-url=${CONTA_COMMAND_DB_URL:jdbc:postgresql://postgres:5432/bantads}
app.datasource.command.username=${CONTA_COMMAND_DB_USER:postgres}
app.datasource.command.password=${CONTA_COMMAND_DB_PASSWORD}
app.datasource.command.driver-class-name=org.postgresql.Driver
app.datasource.command.pool-name=ContaCommandPool

# DataSource do lado query
app.datasource.query.jdbc-url=${CONTA_QUERY_DB_URL:jdbc:postgresql://postgres:5432/bantads}
app.datasource.query.username=${CONTA_QUERY_DB_USER:postgres}
app.datasource.query.password=${CONTA_QUERY_DB_PASSWORD}
app.datasource.query.driver-class-name=org.postgresql.Driver
app.datasource.query.pool-name=ContaQueryPool

# Logs dos pools de conexão
logging.level.com.zaxxer.hikari=INFO