server.port=8080

spring.application.name=ms-gerente

# PostgreSQL
spring.datasource.url=${GERENTE_DB_URL:jdbc:postgresql://postgres:5432/bantads?currentSchema=gerente}
spring.datasource.username=${GERENTE_DB_USER:postgres}
spring.datasource.password=${GERENTE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.pool-name=GerentePool

# JPA / Hibernate
spring.jpa.properties.hibernate.default_schema=gerente
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Logs dos pools
logging.level.com.zaxxer.hikari=INFO
