server.port=8080

spring.application.name=ms-gerente

# Configuração Padrão do PostgreSQL para o ms-cliente
spring.datasource.url=jdbc:postgresql://localhost:5432/cliente_db?currentSchema=cliente
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logs dos pools de conexão
logging.level.com.zaxxer.hikari=INFO