server.port=8080

spring.application.name=ms-cliente

# PostgreSQL
spring.datasource.url=${CLIENTE_DB_URL:jdbc:postgresql://postgres:5432/bantads?currentSchema=cliente}
spring.datasource.username=${CLIENTE_DB_USER:postgres}
spring.datasource.password=${CLIENTE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.pool-name=ClientePool

# JPA / Hibernate
spring.jpa.properties.hibernate.default_schema=cliente
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Logs dos pools
logging.level.com.zaxxer.hikari=INFO
